### ISSUE TITLE
Sometimes, opening W_Spotify crashes the jvm - maybe through appkit.

### ISSUE THREAD

**Issue by Shinkson47** [Shinkson47/UniX6#12]
This only appears to happen on Big Sur, and it doesn't happen all the time.

It will work for some hours, then it will crash for some hours.

```
2022-02-07 12:33:17.586 java[2168:120531] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff205d85bf __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20310bbb objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20600dae -[NSException raise] + 9
	3   AppKit                              0x00007fff22cad872 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007fff22cd5be3 -[NSThemeFrame setStyleMask:] + 142
	5   AppKit                              0x00007fff22cd5986 __25-[NSWindow setStyleMask:]_block_invoke + 2065
	6   AppKit                              0x00007fff22cd511b NSPerformVisuallyAtomicChange + 132
	7   AppKit                              0x00007fff22cd5028 -[NSWindow setStyleMask:] + 170
	8   liblwjgl.dylib                      0x0000000130009cca Java_org_lwjgl_opengl_MacOSXDisplay_nSetResizable + 90
	9   ???                                 0x0000000115126370 0x0 + 4648493936
)
libc++abi: terminating with uncaught exception of type NSException
zsh: abort      java -jar 

```

**Comment by Shinkson47** [comment]
Investigation needed.

A different stack trace whilst demo-ing the game. may be related.

```
Exception in thread "Thread-1" java.lang.IllegalStateException: From thread Thread[Thread-1,5,main]: Thread[LWJGL Application,5,main] already has the context current
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.makeCurrent(ContextGL.java:189)
	at org.lwjgl.opengl.DrawableGL.makeCurrent(DrawableGL.java:110)
	at org.lwjgl.opengl.Display.makeCurrent(Display.java:706)
	at org.lwjgl.opengl.Display.makeCurrentAndSetSwapInterval(Display.java:1025)
	at org.lwjgl.opengl.Display.setDisplayMode(Display.java:251)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setWindowedMode(LwjglGraphics.java:570)
	at com.shinkson47.SplashX6.utility.GraphicalConfig.setDisplayMode(GraphicalConfig.kt:51)
	at com.shinkson47.SplashX6.utility.GraphicalConfig.setFullscreen(GraphicalConfig.kt:83)
	at com.shinkson47.SplashX6.rendering.windows.game.Spotify.spotifyConnect(Spotify.kt:365)
	at com.shinkson47.SplashX6.rendering.windows.game.Spotify.update(Spotify.kt:141)
	at com.shinkson47.SplashX6.rendering.windows.game.Spotify.access$update(Spotify.kt:28)
	at com.shinkson47.SplashX6.rendering.windows.game.Spotify$seekRunnable$1.run(Spotify.kt:315)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by Shinkson47** [comment]
Occoured on my sierra install, too.

However it happened once, then worked perfectly afterwards.
I have no clue what causes this problem.

**Comment by Shinkson47** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fffb125f44e, pid=2789, tid=775
#
# JRE version: OpenJDK Runtime Environment Zulu13.46+15-CA (13.0.10+5) (build 13.0.10+5-MTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu13.46+15-CA (13.0.10+5-MTS, mixed mode, sharing, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [AppKit+0x3a544e]  -[NSApplication _crashOnException:]+0x6d
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Volumes/The Vault/Workspaces/Java/SplashX6/hs_err_pid2789.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by Shinkson47** [comment]
From watching this in the debugger, I ***think*** this was caused by the spotify updater thread attempting to modify the fullscreen state, since it was not on the main thread, which is the only thread with Open GL Context.

This is all hinted the the jvm stacktrace above.

This problem is so temperamental, intermittent, and misleading with the range of different errors produced that i cannot prove this.

For now, i'll assume this is the cause and post this change onto LibGDX's main thread. Seems to make it stable again, so i'll call this closed.
