### ISSUE TITLE
GameHypervisor has no nullsafety on destination selection.

### ISSUE THREAD

**Issue by Shinkson47** [Shinkson47/UniX6#14]
Attempting to path find with no unit selected will crash.

```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.shinkson47.SplashX6.game.GameHypervisor$Companion.unit_setDestination(GameHypervisor.kt:325)
	at com.shinkson47.SplashX6.game.GameHypervisor$Companion.cm_destinationSelect(GameHypervisor.kt:641)
	at com.shinkson47.SplashX6.input.KeyBinder.createGameBinds$lambda-32$lambda-30(KeyBinder.kt:162)
	at com.shinkson47.SplashX6.input.KeyBinder$MatchAndExecute$1.invoke(KeyBinder.kt:261)
	at com.shinkson47.SplashX6.input.KeyBinder$MatchAndExecute$1.invoke(KeyBinder.kt:261)
	at com.shinkson47.SplashX6.input.KeyBinder.poll(KeyBinder.kt:252)
	at com.shinkson47.SplashX6.input.KeyBinder.keyDown(KeyBinder.kt:266)
	at com.badlogic.gdx.InputMultiplexer.keyDown(InputMultiplexer.java:80)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:58)
	at com.badlogic.gdx.backends.lwjgl.DefaultLwjglInput.processEvents(DefaultLwjglInput.java:255)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:220)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

```

**Comment by Shinkson47** [comment]
Fixed in 6a7a067, which implements API validation for REQ_UNIT_SELECTED.
